### PR TITLE
allowing falsy values to be stored

### PR DESCRIPTION
**Pull request by viczam**

### CODE REVIEW

**Comment by marcuspoehls** [comment]
@viczam Hi Victor, thank you for the pull request.

I can see your idea and where this is going. Good catch!
Could you please update the PR and add tests to cover the updated functionality?

Let me know if you’ve questions or need help 😃
Thanks for your help!

**Comment by hueniverse** [comment]
Not sure.

**Comment by marcuspoehls** [comment]
@viczam Hi Victor, I wanna check in if you’re interested in contributing the missing tests to get `catbox-mongodb` test coverage back to 100%.

No problem if not, just let me know by tomorrow 😊

**Comment by marcuspoehls** [comment]
@jardakotesovec Hey Jarda, I’ve a question related to `falsey` value in the cache.

There’s a test that makes sure values like `0` (zero) or the boolean `false` throw an error when getting them. Is this behavior intended?

Here’s the related test: https://github.com/hapijs/catbox-mongodb/blob/master/test/index.js#L724

I want to allow those values, but maybe miss the bigger picture. Can you tell me more about this?

**Comment by jardakotesovec** [comment]
@marcuspoehls Hi, my effort was to handle more mongoDB types - https://github.com/hapijs/catbox-mongodb/blob/master/test/index.js#L73 

So personally I don't see reason why not support Bool. I don't recall if I was considering that at that time.. maybe not because I did not have use case.

Line you are referring is there from beginning and you can see that catbox checks would also go wrong with false value - https://github.com/hapijs/catbox/blob/master/lib/client.js#L72

So first step would be to handle the bool values in catbox level.

**Comment by jardakotesovec** [comment]
And remaining question also would be if any of the existing adapters would actually return false to indicate not having value - that could also break things if it gets changed in catbox.

**Comment by marcuspoehls** [comment]
@jardakotesovec Jarda, thank you for your thoughts.

**Comment by marcuspoehls** [comment]
@viczam I’ve released version `4.1.0` of `catbox-mongodb` that allows you to set falsy values.

Closing this PR, because I used another implementation. I appreciate your PR, it really opened eyes on how to handle falsy values that exceeds the scope of `catbox-mongodb` and influences all catbox adapters. 

Eventually, there will be a [standardized test suite for adapters](https://github.com/hapijs/catbox/issues/196).

Thank you for pointing us to this!

**Pull request closed without merging**
