### PR TITLE
Fixed issue with parsing connection string with replicaSet

### PR DESCRIPTION
**Pull request by itereshchenkov**
**Issue**

In case if MongoDb connection string contains replica set, parsing URI returns an unexpected result. As result, the hosts list will be truncated and contain only the first node.

**Example**

```
this.settings.uri = 'mongodb://bob:password@127.0.0.1:27017,127.0.0.2:27017,127.0.0.3:27017/?maxPoolSize=5&replicaSet=rs';

this.settings.uri = Url.format(Hoek.applyToDefaults(Url.parse(this.settings.uri), { pathname: this.settings.partition }));

// this.settings.uri === 'mongodb://bob:password@127.0.0.1:27017/unit-testing?maxPoolSize=5&replicaSet=rs'
```

This issue relates to the way how `Url.parse` is parsing the urlString. It doesn't parse replica set correctly.

### CODE REVIEW

**Comment by jardakotesovec** [comment]
@itereshchenkov Hi, thanks a lot for PR. I will review it during weekend.

**Comment by jardakotesovec** [comment]
@itereshchenkov Considering the mongodb connection [spec](https://docs.mongodb.com/manual/reference/connection-string/) I noticed one issue. Your regex would not handle `mongodb://bob:password@127.0.0.1:27017,127.0.0.2:27017,127.0.0.3:27017`, which is also valid connection string. 

How about disregard the url module and instead of extracting hosts and putting them there again just replace the database name directly. Looking at the spec I think there are basically 4 situations around database name that can happen:
```
mongodb://bob:password@127.0.0.3:27017
mongodb://bob:password@127.0.0.3:27017/
mongodb://bob:password@127.0.0.3:27017/?options
mongodb://bob:password@127.0.0.3:27017/dbName?options
```

Which can be covered with regex like this:

`this.settings.uri.replace(/(mongodb:\/\/[^\/]*)([^\?]*)(.*)/,`$1/${this.settings.partition}$3`)`

What do you think about this approach?

Also please change version to 3.0.1.

**Comment by itereshchenkov** [comment]
Yes, good catch. I've updated the pull request with the new approach and added some more unit tests.

**Comment by jardakotesovec** [comment]
@itereshchenkov 3.0.1 is published. Thanks a lot for your PR.

**Pull request merged**
