### PR TITLE
fixed licence field in package.json file

### PR DESCRIPTION
**Pull request by simon-p-r**

### CODE REVIEW

**Comment by jardakotesovec** [comment]
Thanks, but can you explain why this should be changed? All other hapi modules has **BSD-3-Clause**.

**Comment by gergoerdosi** [comment]
It is part of the cleanup: https://github.com/hapijs/contrib/issues/31

**Comment by lloydbenson** [comment]
Also confused as isn't that what the PR is doing?  Changing to the BSD-3-Clause like hapi?

**Comment by simon-p-r** [comment]
Npm warns there is no licence file this is why I made change to package.json.

**Comment by jardakotesovec** [comment]
Right, so npm warns about the license also for all hapi modules, right?

Feel free to bring it up in contrib repo..   as it would have to be addressed consistently across hapi modules.

Closing for now.

**Comment by gergoerdosi** [comment]
@jardakotesovec This PR is correct, it should be merged.

**Comment by simon-p-r** [comment]
Sorry but look here for licence file in package.json file https://github.com/hapijs/hapi/blob/master/package.json#L56.  My PR is correct?

**Comment by jardakotesovec** [comment]
Ops.. you are right. Sorry for confusion.

**Pull request merged**
